/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.DaftarUKMController;
import Model.User;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author jorda
 */

public class DaftarUKMPanel extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;
    private User user;
    private DaftarUKMController controller;
    private String prestasiFilePath;

    public DaftarUKMPanel(JScrollPane contentScrollPane, User user) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
        this.user = user;
        this.controller = new DaftarUKMController();
        addActionListener();
    }

    private void addActionListener() {
        openButton.addActionListener(controller.new OpenButtonListener(this));
        kirimButton.addActionListener(controller.new KirimButtonListener(this));
    }

    // Getters for fields to be accessed by the controller
    public JTextField getUkmField() {
        return ukmField;
    }

    public JTextField getKeteranganField() {
        return keteranganField;
    }

    public JTextArea getMotivasiTextArea() {
        return motivasiTextArea;
    }

    public JTextField getFileTextField() {
        return fileTextField;
    }
    
    public void setPrestasiFilePath(String prestasiFilePath) {
        this.prestasiFilePath = prestasiFilePath;
        // Display the file path in a label or text field (assuming you have one)
        // For example, assuming you have a JLabel named prestasiFileLabel
        fileTextField.setText(prestasiFilePath);
    }

    public User getUser() {
        return user;
    }

    // Method to reset fields
    public void resetFields() {
        ukmField.setText("Isikan Nama UKM");
        keteranganField.setText("");
        motivasiTextArea.setText("Isikan Motivasi Anda");
        fileTextField.setText("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryProfilScrollPane = new javax.swing.JScrollPane();
        entryProfilPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ukmField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        motivasiTextArea = new javax.swing.JTextArea();
        keteranganField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kirimButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        entryProfilScrollPane.setBackground(new java.awt.Color(255, 255, 153));
        entryProfilScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        entryProfilScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        entryProfilPanel.setBackground(new java.awt.Color(255, 255, 153));
        entryProfilPanel.setPreferredSize(new java.awt.Dimension(1017, 1100));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Daftar UKM");

        ukmField.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ukmField.setText("Isikan Nama UKM");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("UKM:");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Keterangan:");

        motivasiTextArea.setColumns(20);
        motivasiTextArea.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        motivasiTextArea.setRows(5);
        motivasiTextArea.setText("Isikan Motivasi Anda");
        jScrollPane3.setViewportView(motivasiTextArea);

        keteranganField.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Motivasi:");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Prestasi:");

        openButton.setText("Open File");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Format file: jpeg, jpg, atau png");

        kirimButton.setBackground(new java.awt.Color(51, 102, 255));
        kirimButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kirimButton.setForeground(new java.awt.Color(255, 255, 255));
        kirimButton.setText("Kirim");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setText("Tidak wajib (opsional)");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Tidak wajib (opsional)");

        javax.swing.GroupLayout entryProfilPanelLayout = new javax.swing.GroupLayout(entryProfilPanel);
        entryProfilPanel.setLayout(entryProfilPanelLayout);
        entryProfilPanelLayout.setHorizontalGroup(
            entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryProfilPanelLayout.createSequentialGroup()
                .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entryProfilPanelLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1))
                    .addGroup(entryProfilPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukmField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(entryProfilPanelLayout.createSequentialGroup()
                                .addComponent(keteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(entryProfilPanelLayout.createSequentialGroup()
                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(openButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel6)
                            .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        entryProfilPanelLayout.setVerticalGroup(
            entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryProfilPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukmField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keteranganField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(entryProfilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(111, 111, 111)
                        .addGroup(entryProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openButton)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );

        entryProfilScrollPane.setViewportView(entryProfilPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryProfilScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(entryProfilScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel entryProfilPanel;
    private javax.swing.JScrollPane entryProfilScrollPane;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keteranganField;
    private javax.swing.JButton kirimButton;
    private javax.swing.JTextArea motivasiTextArea;
    private javax.swing.JButton openButton;
    private javax.swing.JTextField ukmField;
    // End of variables declaration//GEN-END:variables
}