/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.DashboardAdminController;
import Controller.HomeController;
import Model.User;
import javax.swing.JScrollPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author jorda
 */
public class HomePanel extends javax.swing.JPanel {
    
    private DashboardAdmin   dashboardAdmin;
    private DashboardClient dashboardClient;
    private User user;
    private JScrollPane contentScrollPane;
    private HomeController controller;
    
    /**
     * Creates new form HomePanel
     */
    
    public HomePanel(JScrollPane contentScrollPane, User user, DashboardAdmin dashboardAdmin) {
        initComponents();
        this.dashboardAdmin = dashboardAdmin;
        this.user = user;
        this.contentScrollPane = contentScrollPane;
        this.controller = new HomeController(this, user, dashboardAdmin);
        controller.displayFullname();
        setTextPaneAlignment();
        addActionListener();

        if (user.isAdmin() == 1) {
            jLabel3.setVisible(false);  
            profilButton.setVisible(false);
        }
    }
        
    public HomePanel(JScrollPane contentScrollPane, User user, DashboardClient dashboardClient) {
        initComponents();
        this.dashboardClient = dashboardClient;
        this.user = user;
        this.contentScrollPane = contentScrollPane;
        this.controller = new HomeController(this, user, dashboardClient);
        controller.displayFullname();
        setTextPaneAlignment();
        addActionListener();

        if (user.isAdmin() == 1) {
            jLabel3.setVisible(false);  
            profilButton.setVisible(false);
        }
    }
    
    private void addActionListener() {
        profilButton.addActionListener(controller.new profilButtonListener(this));
    }

    public JScrollPane getContentScrollPane() {
        return contentScrollPane;
    }

    public void setFullname(String fullname) {
        tampilfullname.setText(fullname);
    }
    
    public void displayFullname(User user) {
        String fullname = user.getFullname();
        if (fullname != null) {
            tampilfullname.setText(fullname);
        } else {
            tampilfullname.setText("User");
        }
    }
    
    private void setTextPaneAlignment() {
        // Setting text alignment to center
        StyledDocument doc = tampilfullname.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tampilfullname = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        profilButton = new javax.swing.JButton();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 153));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        homePanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setText("Welcome To The Dashboard ");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tampilfullname.setEditable(false);
        tampilfullname.setBackground(new java.awt.Color(255, 255, 153));
        tampilfullname.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        tampilfullname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tampilfullname.setFocusable(false);
        jScrollPane3.setViewportView(tampilfullname);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("Silahkan melengkapi data diri jika Anda belum melakukannya");

        profilButton.setBackground(new java.awt.Color(255, 255, 153));
        profilButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        profilButton.setForeground(new java.awt.Color(0, 153, 255));
        profilButton.setText("Lengkapi Data Diri");
        profilButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilButton)
                    .addComponent(jLabel3)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(homePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton profilButton;
    private javax.swing.JTextPane tampilfullname;
    // End of variables declaration//GEN-END:variables
}
